import React, { createContext, useContext, useEffect, useMemo, useState } from 'react'

const translations = {
  EN: {
    home:'Home', about:'About Us', offer:'What We Offer', serve:'What We Serve', solution:'Our Solution', contact:'Contact',
    create:'Create Account', login:'Login', dashboard:'Dashboard', overview:'Overview', farms:'My Farms', soil:'Soil Diagnosis', weather:'Weather', advisor:'AI Advisor', crop:'Crop Recommendation', notifications:'Notifications', profile:'Profile', settings:'Settings', logout:'Logout', workspace:'Workspace',
    goodMorning:'Good morning, Maduhu ', today:'Here is what is happening with your farm today.',
    soilPh:'Soil pH', waterPh:'Water pH', nitrogen:'Nitrogen (N)', phosphorus:'Phosphorus (P)', potassium:'Potassium (K)', humidity:'Humidity', temperature:'Temperature', rainfall:'Rainfall',
    normal:'Normal', good:'Good', attention:'Attention', optimal:'Optimal', healthy:'Healthy',
    farmHealth:'Farm Health', cropRecommendation:'Crop Recommendation', aiInsight:'AI Insight', openSoil:'Open Soil Diagnosis',
    preferences:'Preferences', appearance:'Appearance', appearanceDesc:'Choose how AgriSense AI looks.', system:'System', light:'Light', dark:'Dark', notificationsDesc:'Receive important farm alerts.', privacy:'Privacy & Security', privacyDesc:'Manage your account and data preferences.', workspaceTitle:'Workspace', workspaceDesc:'Your central place for farms, insights, documents and account tools.', workspaceSettings:'Workspace Settings', workspaceSettingsDesc:'Quick controls for appearance, language, notifications and account preferences.', privacyPageTitle:'Privacy & Security', privacyPageDesc:'Manage privacy, account security and data controls in one place.', twoFactor:'Two-factor authentication', sessionManagement:'Session management', dataPrivacy:'Data privacy', activeSessions:'Active sessions', deleteAccount:'Delete account',
    language:'Language', english:'English', kiswahili:'Kiswahili', languageDesc:'Choose your preferred language.',
    welcome:'Welcome back', continueDashboard:'Continue to your farm intelligence dashboard.', startProfile:'Start building your smart farm profile.', firstName:'First name', lastName:'Last name', email:'Email', password:'Password', forgot:'Forgot password?', access:'Access Dashboard', agree:'I agree to the', terms:'terms and privacy practices.', or:'OR', google:'Continue with Google',
    farmsTitle:'My Farms', addFarm:'Add Farm', farmName:'Farm name', size:'Farm size (hectares)', soilType:'Soil type', soilTexture:'Soil texture', location:'Location', gps:'Use current GPS', saveFarm:'Save Farm', cancel:'Cancel', view:'View', edit:'Edit', noFarms:'No farms yet. Add your first farm to start monitoring.',
    diagnosis:'Diagnostics', diagnosisDesc:'Monitor water pH, nutrients, humidity and temperature for soil diagnosis.', exactTitle:'Validated recommendation pipeline', exactDesc:'The production AI can return a validated application rate per hectare or per planting hole after crop, soil results, agronomic rules and product concentration are known. This demo does not invent a real fertilizer prescription.',
    climate:'Farm Climate', current:'Current Conditions', clear:'Clear / comfortable', wind:'Wind',
    intelligence:'Intelligence', askFarm:'Ask about your farm...', advisorWelcome:'Hello! I am your AgriSense AI Advisor. Ask about crop selection, soil readings, irrigation or farm monitoring.', demoResponse:'Demo response: this message will be replaced by your connected AI backend/model.',
    aiEngine:'AI Engine', cropDesc:'Enter soil and environmental readings used by the crop recommendation model.', analyze:'Analyze with AI', analyzing:'Analyzing...', demoResult:'Demo Result', suitability:'suitability', modelNote:'Demo frontend result. Replace this response with your trained model API response when the backend is connected.',
    updates:'Updates', sensorReady:'Sensor integration ready', sensorReadyDesc:'Connect the backend to receive live multi-sensor events.', nutrientAlert:'Soil nutrient attention', nutrientAlertDesc:'Potassium reading needs review.', stable:'Farm health stable', stableDesc:'Your current dashboard readings are within the demo safe range.',
    account:'Account', farmerProfile:'Farmer Profile', uploadPhoto:'Upload a profile picture up to 5 MB.', saveProfile:'Save Profile', saved:'Saved',
    contactTitle:'Let’s connect.', contactDesc:'Use any of the channels below. Replace the placeholder project accounts in src/data.js with your official accounts.', officialChannel:'Official channel', officialPage:'Official page', chatWhatsapp:'Chat on WhatsApp', call:'Call', privacyTitle:'Your farm data should stay under your control.', privacyText:'This starter UI does not send your farm information to a third party by itself. When the backend is added, define authentication, consent, data retention and sensor-data security policies before production use.',
    heroTitle:'Smarter farming with AI-powered soil intelligence', heroDesc:'AgriSense AI helps farmers make data-driven decisions for healthier soil, better yields and sustainable agriculture.', getStarted:'Get Started', watch:'Watch Overview', aboutTitle:'Built for better farm decisions', aboutText:'AgriSense AI brings soil intelligence, farm monitoring and AI recommendations into one clear workflow.', solutionTitle:'From sensor readings to smarter action', solutionText:'A connected workflow designed for multi-sensor IoT, backend services and validated AI models.', impact:'Our Impact', productivity:'Increased Productivity', sustainability:'Environmental Care', food:'Food Security', productivityText:'Better crop decisions', sustainabilityText:'Healthier soil & ecosystem', foodText:'More resilient farm output', ready:'Ready to start?', readyTitle:'Build a smarter farm profile.', farmManagement:'Farm management', registerReview:'Register, review and update your farm profiles.', farmSetup:'Farm setup', gpsDenied:'GPS permission denied', gpsHint:'GPS coordinates will appear here after permission is granted.', sendMessage:'Send Message', messageReady:'Message ready', helpTitle:'Tell us how we can help.', demoForm:'Demo contact form. Connect EmailJS/backend before production.', social:'Social',
  },
  SW: {
    home:'Mwanzo', about:'Kuhusu Sisi', offer:'Tunachotoa', serve:'Tunachohudumia', solution:'Suluhisho Letu', contact:'Mawasiliano',
    create:'Fungua Akaunti', login:'Ingia', dashboard:'Dashibodi', overview:'Muhtasari', farms:'Mashamba Yangu', soil:'Utambuzi wa Udongo', weather:'Hali ya Hewa', advisor:'Mshauri wa AI', crop:'Mapendekezo ya Mazao', notifications:'Arifa', profile:'Wasifu', settings:'Mipangilio', logout:'Toka', workspace:'Eneo la Kazi',
    goodMorning:'Habari za asubuhi, Maduhu ', today:'Haya ndiyo yanayoendelea kwenye shamba lako leo.',
    soilPh:'pH ya Udongo', waterPh:'pH ya Maji', nitrogen:'Nitrojeni (N)', phosphorus:'Fosforasi (P)', potassium:'Potasiamu (K)', humidity:'Unyevunyevu wa Hewa', temperature:'Joto', rainfall:'Mvua',
    normal:'Kawaida', good:'Nzuri', attention:'Tahadhari', optimal:'Bora', healthy:'Lenye Afya', farmHealth:'Afya ya Shamba', cropRecommendation:'Mapendekezo ya Zao', aiInsight:'Ushauri wa AI', openSoil:'Fungua Utambuzi wa Udongo',
preferences:'Mapendeleo', appearance:'Muonekano', appearanceDesc:'Chagua jinsi AgriSense AI ionekane.', system:'Mfumo', light:'Mwanga', dark:'Giza', notificationsDesc:'Pokea arifa muhimu za shamba.', privacy:'Faragha na Usalama', privacyDesc:'Simamia akaunti na mapendeleo ya data.', workspaceTitle:'Eneo la Kazi', workspaceDesc:'Sehemu kuu ya kusimamia mashamba, taarifa, nyaraka na zana za akaunti.', workspaceSettings:'Mipangilio ya Eneo la Kazi', workspaceSettingsDesc:'Dhibiti muonekano, lugha, arifa na mapendeleo ya akaunti.', privacyPageTitle:'Faragha na Usalama', privacyPageDesc:'Simamia faragha, usalama wa akaunti na udhibiti wa data sehemu moja.', twoFactor:'Uthibitishaji wa hatua mbili', sessionManagement:'Usimamizi wa vikao', dataPrivacy:'Faragha ya data', activeSessions:'Vikao vinavyotumika', deleteAccount:'Futa akaunti', language:'Lugha', english:'English', kiswahili:'Kiswahili', languageDesc:'Chagua lugha unayoipendelea.',
    welcome:'Karibu tena', continueDashboard:'Endelea kwenye dashibodi yako ya taarifa za shamba.', startProfile:'Anza kujenga wasifu wa shamba lako.', firstName:'Jina la kwanza', lastName:'Jina la mwisho', email:'Barua pepe', password:'Nenosiri', forgot:'Umesahau nenosiri?', access:'Fungua Dashibodi', agree:'Nakubaliana na', terms:'masharti na sera za faragha.', or:'AU', google:'Endelea na Google',
    farmsTitle:'Mashamba Yangu', addFarm:'Ongeza Shamba', farmName:'Jina la shamba', size:'Ukubwa wa shamba (hekta)', soilType:'Aina ya udongo', soilTexture:'Muundo wa udongo', location:'Mahali', gps:'Tumia GPS ya sasa', saveFarm:'Hifadhi Shamba', cancel:'Ghairi', view:'Tazama', edit:'Hariri', noFarms:'Bado hakuna mashamba. Ongeza shamba lako la kwanza kuanza ufuatiliaji.',
    diagnosis:'Utambuzi', diagnosisDesc:'Fuatilia pH ya maji, virutubisho, unyevunyevu wa hewa na joto kwa ajili ya utambuzi wa udongo.', exactTitle:'Mfumo wa mapendekezo uliothibitishwa', exactDesc:'AI ya uzalishaji inaweza kutoa kiasi kilichothibitishwa kwa hekta au kwa shimo baada ya kujua zao, majibu ya udongo, kanuni za kilimo na mkusanyiko wa bidhaa. Demo hii haitengenezi agizo halisi la mbolea.',
    climate:'Hali ya Hewa ya Shamba', current:'Hali ya Sasa', clear:'Angavu / nzuri', wind:'Upepo', intelligence:'Akili Bandia', askFarm:'Uliza kuhusu shamba lako...', advisorWelcome:'Habari! Mimi ni Mshauri wako wa AgriSense AI. Uliza kuhusu uchaguzi wa zao, vipimo vya udongo, umwagiliaji au ufuatiliaji wa shamba.', demoResponse:'Jibu la demo: ujumbe huu utabadilishwa na backend/model yako ya AI itakapounganishwa.',
    aiEngine:'Injini ya AI', cropDesc:'Ingiza vipimo vya udongo na mazingira vinavyotumiwa na mfumo wa kupendekeza mazao.', analyze:'Chambua kwa AI', analyzing:'Inachambua...', demoResult:'Matokeo ya Demo', suitability:'ufanisi', modelNote:'Haya ni matokeo ya frontend demo. Badilisha jibu hili na response ya trained model API backend itakapounganishwa.',
    updates:'Taarifa', sensorReady:'Muunganisho wa sensor uko tayari', sensorReadyDesc:'Unganisha backend kupokea matukio ya moja kwa moja kutoka multi-sensor.', nutrientAlert:'Tahadhari ya virutubisho', nutrientAlertDesc:'Kipimo cha potasiamu kinahitaji kuangaliwa.', stable:'Afya ya shamba iko vizuri', stableDesc:'Vipimo vya sasa viko ndani ya kiwango salama cha demo.',
    account:'Akaunti', farmerProfile:'Wasifu wa Mkulima', uploadPhoto:'Pakia picha ya wasifu isiyozidi 5 MB.', saveProfile:'Hifadhi Wasifu', saved:'Imehifadhiwa', contactTitle:'Tuunganishe.', contactDesc:'Tumia njia yoyote hapa chini. Badilisha akaunti za mfano kwenye src/data.js na akaunti rasmi za mradi.', officialChannel:'Kituo rasmi', officialPage:'Ukurasa rasmi', chatWhatsapp:'Wasiliana WhatsApp', call:'Piga Simu', privacyTitle:'Taarifa za shamba lako zibaki chini ya udhibiti wako.', privacyText:'Frontend hii ya mwanzo haitumi taarifa za shamba lako kwa mtu wa tatu yenyewe. Backend ikiongezwa, weka sera za authentication, ridhaa, uhifadhi wa data na usalama wa sensor kabla ya uzalishaji.',
    heroTitle:'Kilimo bora kwa akili ya AI ya udongo', heroDesc:'AgriSense AI huwasaidia wakulima kufanya maamuzi yanayotegemea data kwa udongo wenye afya, mavuno bora na kilimo endelevu.', getStarted:'Anza Sasa', watch:'Tazama Muhtasari', aboutTitle:'Imejengwa kwa maamuzi bora ya shamba', aboutText:'AgriSense AI huleta taarifa za udongo, ufuatiliaji wa shamba na mapendekezo ya AI katika mtiririko mmoja ulio wazi.', solutionTitle:'Kutoka vipimo vya sensor hadi hatua sahihi', solutionText:'Mtiririko uliotengenezwa kwa multi-sensor IoT, backend services na AI models zilizothibitishwa.', impact:'Matokeo Yetu', productivity:'Uzalishaji Umeongezeka', sustainability:'Utunzaji wa Mazingira', food:'Usalama wa Chakula', productivityText:'Maamuzi bora ya zao', sustainabilityText:'Udongo na mazingira yenye afya', foodText:'Mavuno imara zaidi', ready:'Uko tayari kuanza?', readyTitle:'Jenga wasifu bora wa shamba lako.', farmManagement:'Usimamizi wa shamba', registerReview:'Sajili, kagua na sasisha taarifa za mashamba yako.', farmSetup:'Usanidi wa shamba', gpsDenied:'Ruhusa ya GPS imekataliwa', gpsHint:'Viwianishi vya GPS vitaonekana hapa baada ya kutoa ruhusa.', sendMessage:'Tuma Ujumbe', messageReady:'Ujumbe uko tayari', helpTitle:'Tuambie tunawezaje kusaidia.', demoForm:'Fomu ya demo. Unganisha EmailJS/backend kabla ya uzalishaji.', social:'Mitandao ya kijamii',
  }
}

const LanguageContext = createContext(null)
export function LanguageProvider({children}) {
  const [lang, setLang] = useState(() => localStorage.getItem('agrisense-lang') || 'EN')
  useEffect(() => { localStorage.setItem('agrisense-lang', lang); document.documentElement.lang = lang === 'SW' ? 'sw' : 'en' }, [lang])
  const value = useMemo(() => ({ lang, setLang, t:(key) => translations[lang]?.[key] ?? translations.EN[key] ?? key }), [lang])
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}
export function useLanguage(){ return useContext(LanguageContext) }
